import { Menu, Tv } from 'lucide-react';
import { ThemeToggle } from './theme-toggle';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from './ui/dropdown-menu';
import { Button } from './ui/button';

export function Header() {
  return (
      <header className="fixed top-0 left-0 right-0 z-50 border-b bg-background/80 backdrop-blur-sm">
            <div className="container flex h-16 items-center justify-between px-4 md:px-6">
                    {/* Grup Kiri: Logo (Selalu Terlihat) */}
                            <div className="flex items-center gap-3">
                                      <Tv className="h-7 w-7 text-primary" />
                                                <span className="text-xl font-bold tracking-tight">
                                                            KlikPlay
                                                                      </span>
                                                                              </div>

                                                                                      {/* Grup Kanan: Kontrol (Tata Letak Disesuaikan per Ukuran Layar) */}
                                                                                              <div className="flex items-center gap-2">
                                                                                                        {/* Navigasi Desktop (Disembunyikan di Mobile) */}
                                                                                                                  <nav className="hidden md:flex md:items-center md:gap-4">
                                                                                                                              {/* Link navigasi desktop akan ditambahkan di sini */}
                                                                                                                                        </nav>

                                                                                                                                                  {/* Tombol Tema (Selalu Terlihat) */}
                                                                                                                                                            <ThemeToggle />

                                                                                                                                                                      {/* Menu Hamburger (Hanya Terlihat di Mobile) */}
                                                                                                                                                                                <div className="md:hidden">
                                                                                                                                                                                            <DropdownMenu>
                                                                                                                                                                                                          <DropdownMenuTrigger asChild>
                                                                                                                                                                                                                          <Button variant="outline" size="icon">
                                                                                                                                                                                                                                            <Menu className="h-5 w-5" />
                                                                                                                                                                                                                                                              <span className="sr-only">Toggle Menu</span>
                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                            </DropdownMenuTrigger>
                                                                                                                                                                                                                                                                                                          <DropdownMenuContent 
                                                                                                                                                                                                                                                                                                                          align="end" 
                                                                                                                                                                                                                                                                                                                                          className="w-[calc(100vw-2rem)] sm:w-64"
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                        {/* Konten menu akan ditambahkan di sini */}
                                                                                                                                                                                                                                                                                                                                                                                        <DropdownMenuItem>
                                                                                                                                                                                                                                                                                                                                                                                                          <span>(Navigasi Mobile)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                          </DropdownMenuItem>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </DropdownMenuContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </DropdownMenu>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }