import { Play, Code } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export function HeroSection() {
  return (
      <section 
            id="hero" 
                  className="relative flex min-h-[calc(100vh-4rem)] items-center justify-center overflow-hidden py-20"
                      >
                            {/* Animated Background Blobs */}
                                  <div className="absolute inset-0 -z-10">
                                          <div className="absolute -top-20 -left-20 h-96 w-96 rounded-full bg-primary/20 blur-3xl animate-blob-float [animation-delay:_-3s]"></div>
                                                  <div className="absolute -bottom-20 -right-20 h-96 w-96 rounded-full bg-purple-500/20 blur-3xl animate-blob-float [animation-delay:_-6s]"></div>
                                                        </div>
                                                              
                                                                    <div className="container px-4 text-center">
                                                                            <div className="flex flex-col items-center space-y-8">
                                                                                      
                                                                                                {/* Main Heading */}
                                                                                                          <h1 className="text-5xl font-extrabold tracking-tighter sm:text-6xl md:text-7xl lg:text-8xl">
                                                                                                                      <span className="block text-slate-700 dark:text-slate-300">Welcome to</span>
                                                                                                                                  <span className="block bg-gradient-to-r from-primary via-purple-500 to-pink-500 bg-clip-text text-transparent">
                                                                                                                                                KlikPlay
                                                                                                                                                            </span>
                                                                                                                                                                      </h1>

                                                                                                                                                                                {/* Subheading */}
                                                                                                                                                                                          <p className="max-w-3xl text-lg text-slate-600 dark:text-slate-400 md:text-xl">
                                                                                                                                                                                                      Your ultimate destination for movies, TV shows, and anime. Stream your favorites with our advanced customizable player.
                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                          {/* Call-to-Action Buttons */}
                                                                                                                                                                                                                                    <div className="flex flex-col flex-wrap justify-center gap-4 sm:flex-row">
                                                                                                                                                                                                                                                <Button asChild size="lg" className="gap-2 text-lg">
                                                                                                                                                                                                                                                              <Link href="#player">
                                                                                                                                                                                                                                                                              <Play className="h-5 w-5" />
                                                                                                                                                                                                                                                                                              Start Watching
                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                    <Button asChild size="lg" variant="outline" className="gap-2 text-lg">
                                                                                                                                                                                                                                                                                                                                                  <Link href="#docs">
                                                                                                                                                                                                                                                                                                                                                                  <Code className="h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                                                                  Explore API
                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                            </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                          }